export type SubmissionPayload={leetcodeId:number;title:string;slug:string;url:string;difficulty:'Easy'|'Medium'|'Hard';language:string;solvedAt:string;submissionId?:string;topics?:string[]};
const DIFFICULTIES=['Easy','Medium','Hard'] as const;
type Difficulty=typeof DIFFICULTIES[number];
type MetadataFailure='title'|'leetcodeId'|'difficulty';
type Metadata={leetcodeId:number;title:string;slug:string;url:string;difficulty:Difficulty;topics?:string[]};
type MetadataSources={title:string;leetcodeId:string;difficulty:string};
type MetadataResult={metadata:Metadata|null;failure?:MetadataFailure;sources?:MetadataSources};
function normalize(text:string){return text.replace(/\s+/g,' ').trim();}
export function isAccepted(text:string){return normalize(text).toLowerCase()==='accepted';}
function cleanTitle(text:string){return normalize(text).replace(/^\d{1,5}\.\s*/,'').replace(/\s*[-|].*$/,'').trim();}
function pageText(doc:Document){return normalize(doc.body?.innerText||doc.body?.textContent||'');}
function numberedCandidate(text:string){const match=normalize(text).match(/^(\d{1,5})\.\s*(.+)$/);return match?{id:Number(match[1]),title:cleanTitle(match[2])}:null;}
function getSlug(url:string){return url.match(/\/problems\/([^/?#]+)/)?.[1];}
function getSubmissionId(url:string){return url.match(/\/submissions\/(?:detail\/)?(\d+)/)?.[1];}
function getSubmissionIdFromPage(doc:Document,result?:Element){const values=[getSubmissionId(location.href),result?.getAttribute('data-submission-id'),result?.getAttribute('data-submissionid'),...Array.from(doc.querySelectorAll('a[href*="/submissions/"]')).map(link=>getSubmissionId(link.getAttribute('href')||''))].filter(Boolean);return values[0];}
function structuredText(doc:Document){return Array.from(doc.querySelectorAll('script[type="application/ld+json"],script:not([src])')).map(script=>script.textContent||'').join('\n');}
function structuredValue(text:string,keys:string[]){const keyPattern=keys.join('|');return text.match(new RegExp(`"(?:${keyPattern})"\\s*:\\s*"?([^",}]+)`, 'i'))?.[1]?.trim();}
function isLanguageLabel(text:string){return /^(cpp|c\+\+|cxx|python|python3|java|javascript|js|typescript|ts|csharp|c#|go|golang|rust|kotlin|swift|php|ruby|scala|dart|mysql|mssql|oracle sql|postgresql)$/i.test(normalize(text));}
function titleFromSlug(slug:string){return slug.split('-').map(word=>word?word[0].toUpperCase()+word.slice(1):word).join(' ');}
function getTopics(doc:Document){const topics=Array.from(doc.querySelectorAll('a[href*="/tag/"],a[href*="/topics/"],[data-cy="topic-tag"],[data-testid="topic-tag"]')).filter(isVisible).map(element=>normalize(element.textContent||'')).filter(topic=>topic&&!/^topics?$/i.test(topic));const embedded=Array.from(doc.querySelectorAll('script:not([src])')).map(script=>script.textContent||'').flatMap(text=>Array.from(text.matchAll(/"topicTags"\s*:\s*\[([\s\S]*?)\]/g)).flatMap(match=>Array.from(match[1].matchAll(/"name"\s*:\s*"([^"]+)"/g)).map(name=>name[1])));return Array.from(new Set([...topics,...embedded.map(normalize).filter(Boolean)]));}
function buildMetadata(doc:Document,url=location.href):MetadataResult{
  const slug=getSlug(url);if(!slug)return {metadata:null,failure:'title'};
  const headings=Array.from(doc.querySelectorAll('h1,h2,h3,[role="heading"]'));
  const links=Array.from(doc.querySelectorAll('a[href*="/problems/"]')).filter(link=>{const href=link.getAttribute('href')||'';return getSlug(href)===slug;});
  const numbered=[...headings,...links].map(element=>numberedCandidate(element.textContent||'')).find(candidate=>candidate&&!isLanguageLabel(candidate.title));
  const headingTitle=[...headings,...links].map(element=>cleanTitle(element.textContent||'')).find(title=>title&&!isLanguageLabel(title)&&!/^Accepted|Wrong Answer|Pending$/i.test(title));
  const metaTitle=doc.querySelector('meta[property="og:title"],meta[name="title"]')?.getAttribute('content')||'';
  const structured=structuredText(doc);const structuredTitle=cleanTitle(structuredValue(structured,['title','name'])||'');
  const title=numbered?.title||headingTitle||(!isLanguageLabel(structuredTitle)&&structuredTitle)||(!isLanguageLabel(cleanTitle(metaTitle))&&cleanTitle(metaTitle))||(!isLanguageLabel(cleanTitle(doc.title))&&cleanTitle(doc.title))||titleFromSlug(slug);
  const titleSource=numbered?.title?'numbered heading/link':headingTitle?'heading/link':structuredTitle?'structured metadata':metaTitle?'page metadata':doc.title?'document title':'URL slug';
  const text=pageText(doc);const escapedTitle=title.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
  const numberFromContent=text.match(new RegExp(`(?:^|\\s)(\\d{1,5})\\.\\s+${escapedTitle}(?:\\s|$)`,'i'));const numberFromLabel=text.match(/\bproblem\s*#?\s*(\d{1,5})\b/i);const structuredNumber=structuredValue(structured,['questionFrontendId','frontendQuestionId','problemNumber','questionNumber']);
  const leetcodeId=numbered?.id||Number(numberFromContent?.[1]||numberFromLabel?.[1]||structuredNumber||0);const numberSource=numbered?.id?'numbered heading/link':numberFromContent?'page content':numberFromLabel?'problem label':structuredNumber?'structured metadata':'';
  const difficultyElements=Array.from(doc.querySelectorAll('[data-difficulty], [aria-label*="difficulty" i], [class*="difficulty" i], [data-e2e-locator*="difficulty" i], [data-testid*="difficulty" i]'));const domDifficulty=DIFFICULTIES.find(level=>difficultyElements.some(element=>normalize(`${element.textContent||''} ${element.getAttribute('aria-label')||''}`).toLowerCase().includes(level.toLowerCase())));const structuredDifficulty=structuredValue(structured,['difficulty','level']);const scriptDifficulty=structured.match(/"difficulty"\s*:\s*"(Easy|Medium|Hard)"/i)?.[1] as Difficulty|undefined;const difficulty=(domDifficulty||structuredDifficulty&&DIFFICULTIES.find(level=>level.toLowerCase()===structuredDifficulty.toLowerCase())||scriptDifficulty||DIFFICULTIES.find(level=>new RegExp(`\\b${level}\\b`,'i').test(text))) as Difficulty|undefined;const difficultySource=domDifficulty?'difficulty DOM':structuredDifficulty||scriptDifficulty?'structured metadata':difficulty?'page text':'';
  const sources={title:titleSource,leetcodeId:numberSource,difficulty:difficultySource};if(!title)return {metadata:null,failure:'title',sources};if(!leetcodeId)return {metadata:null,failure:'leetcodeId',sources};if(!difficulty)return {metadata:null,failure:'difficulty',sources};const topics=getTopics(doc);return {metadata:{leetcodeId,title,slug,url:`https://leetcode.com/problems/${slug}/`,difficulty,...(topics.length?{topics}: {})},failure:undefined,sources};
}
export function extractMetadata(doc:Document,url=location.href){return buildMetadata(doc,url).metadata;}
function isVisible(element:Element){if(element.hasAttribute('hidden')||element.getAttribute('aria-hidden')==='true')return false;const style=getComputedStyle(element);return style.display!=='none'&&style.visibility!=='hidden';}
function getLanguage(doc:Document){
  const aliases:Record<string,string>={cpp:'C++',cxx:'C++',python:'Python',python3:'Python',java:'Java',javascript:'JavaScript',js:'JavaScript',typescript:'TypeScript',ts:'TypeScript',csharp:'C#',cs:'C#',golang:'Go',go:'Go',rust:'Rust',kotlin:'Kotlin',swift:'Swift',php:'PHP',ruby:'Ruby',scala:'Scala',dart:'Dart',mysql:'MySQL',mssql:'MS SQL',oraclesql:'Oracle SQL',postgresql:'PostgreSQL'};const labels=['C++','Python','JavaScript','TypeScript','Java','C#','Go','Rust','Kotlin','Swift','PHP','Ruby','Scala','Dart','MySQL','MS SQL','Oracle SQL','PostgreSQL','C'];const selectors=['[data-mode-id]','[data-language]','[data-language-id]','[data-e2e-locator*="language" i]','[data-testid*="language" i]','[aria-label*="language" i]','[title*="language" i]','[class*="language" i]','button,[role="combobox"],select'];const seen=new Set<Element>();
  for(const selector of selectors){for(const element of Array.from(doc.querySelectorAll(selector))){if(seen.has(element)||!isVisible(element))continue;seen.add(element);const values=[element.getAttribute('data-mode-id'),element.getAttribute('data-language'),element.getAttribute('data-language-id'),element.getAttribute('aria-label'),element.getAttribute('title'),(element as HTMLSelectElement).value,element.textContent].filter(Boolean).map(value=>normalize(value as string));for(const value of values){const key=value.toLowerCase().replace(/[^a-z0-9]+/g,'').replace(/^language/,'');if(aliases[key])return aliases[key];const label=labels.find(candidate=>value.toLowerCase()===candidate.toLowerCase()||value.toLowerCase().startsWith(`${candidate.toLowerCase()} `));if(label)return label;}}}return 'Unknown';
}
export function observeAccepted(callback:(p:SubmissionPayload)=>void){
  const processedSubmissionIds=new Set<string>();const baselineSubmissionIds=new Set<string>();let scanTimer:number|undefined;let lastMutationAt=performance.now();let ready=false;let lastDiagnostic='';const quietPeriod=750;
  const diagnostic=(message:string)=>{if(lastDiagnostic!==message){console.warn(`[DSA Tracker] ${message}`);lastDiagnostic=message;}};
  const scan=()=>{scanTimer=undefined;console.log('[DSA Tracker] Scanning submission page...');const result=Array.from(document.querySelectorAll('[data-e2e-locator="submission-result"], [data-testid="submission-result"]')).find(element=>isVisible(element)&&isAccepted(element.textContent||''));const submissionId=result?getSubmissionIdFromPage(document,result):undefined;
    if(!ready){if(submissionId&&!baselineSubmissionIds.has(submissionId)){baselineSubmissionIds.add(submissionId);processedSubmissionIds.add(submissionId);console.log('[DSA Tracker] Establishing initial submission baseline:',submissionId);}if(document.readyState==='complete'&&performance.now()-lastMutationAt>=quietPeriod){ready=true;console.log('[DSA Tracker] Detector ready');}if(!result)diagnostic('Accepted result not found during initialization');scheduleScan();return;}
    if(!result){diagnostic('Accepted result not found');return;}console.log('[DSA Tracker] Accepted result found');if(!submissionId){diagnostic('Accepted result has no submission ID; waiting for a new submission');return;}if(processedSubmissionIds.has(submissionId)){diagnostic(`Submission ${submissionId} already processed`);return;}console.log('[DSA Tracker] New submission detected:',submissionId);const extracted:MetadataResult=buildMetadata(document);if(!extracted.metadata){diagnostic(`Metadata extraction failed: ${extracted.failure||'unknown'}`);return;}lastDiagnostic='';const metadata=extracted.metadata;console.log('[DSA Tracker] Metadata sources:',extracted.sources);console.log('[DSA Tracker] Metadata extracted:',{leetcodeId:metadata.leetcodeId,title:metadata.title,slug:metadata.slug,difficulty:metadata.difficulty});processedSubmissionIds.add(submissionId);const language=getLanguage(document);const payload={...metadata,language,solvedAt:new Date().toISOString(),submissionId};console.log('[DSA Tracker] Accepted detected');console.log(`[DSA Tracker] Problem: ${payload.title}`);console.log('[DSA Tracker] Submission ID:',submissionId);console.log('[DSA Tracker] Submission language:',language);console.log('[DSA Tracker] Payload:',payload);callback(payload);
  };
  const scheduleScan=(fromMutation=false)=>{if(fromMutation)lastMutationAt=performance.now();if(scanTimer===undefined)scanTimer=window.setTimeout(scan,ready?100:Math.max(100,quietPeriod-(performance.now()-lastMutationAt)))};
  console.log('[DSA Tracker] Detector initializing...');const initialUrlSubmissionId=getSubmissionId(location.href);if(initialUrlSubmissionId){baselineSubmissionIds.add(initialUrlSubmissionId);processedSubmissionIds.add(initialUrlSubmissionId);console.log('[DSA Tracker] Establishing initial submission baseline:',initialUrlSubmissionId);}scheduleScan();new MutationObserver(()=>scheduleScan(true)).observe(document.body,{subtree:true,childList:true,characterData:true});window.addEventListener('popstate',()=>scheduleScan(true));window.addEventListener('hashchange',()=>scheduleScan(true));for(const method of ['pushState','replaceState'] as const){const original=history[method];history[method]=function(...args){const result=original.apply(this,args);scheduleScan(true);return result};}
}
