import { useEffect, useMemo, useRef, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import AppHeader from '../components/AppHeader';
import { api } from '../services/api';
import type { SolvedProblem } from '../types';

type Toast = { id: string; item: SolvedProblem; record: Record<string, unknown> | null; message: string; restoring: boolean; error: boolean };
const platformLabel = (platform?: string) => platform === 'leetcode' || !platform ? 'LeetCode' : platform;
const languageLabel = (language?: string) => language?.trim() || 'Unknown';

export default function Problems() { const [items, setItems] = useState<SolvedProblem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [search, setSearch] = useState(''); const [platform, setPlatform] = useState('All'); const [language, setLanguage] = useState('All'); const [difficulty, setDifficulty] = useState('All'); const [sort, setSort] = useState('newest'); const [deleting, setDeleting] = useState<Set<string>>(new Set()); const [toasts, setToasts] = useState<Toast[]>([]); const timers = useRef(new Map<string, number>());
  const load = () => { setLoading(true); return api.problems().then(response => setItems(response.items)).catch(e => setError(e.message)).finally(() => setLoading(false)); }; useEffect(() => { void load(); }, []); useEffect(() => () => timers.current.forEach(timer => window.clearTimeout(timer)), []);
  const languages = useMemo(() => Array.from(new Set(items.map(item => languageLabel(item.language)))).sort(), [items]); const shown = useMemo(() => items.filter(item => platform === 'All' || platformLabel(item.platform) === platform).filter(item => language === 'All' || languageLabel(item.language) === language).filter(item => difficulty === 'All' || item.problemId.difficulty === difficulty).filter(item => item.problemId.title.toLowerCase().includes(search.toLowerCase()) || String(item.problemId.leetcodeId).includes(search)).sort((a, b) => sort === 'oldest' ? +new Date(a.solvedAt) - +new Date(b.solvedAt) : sort === 'numberAsc' ? a.problemId.leetcodeId - b.problemId.leetcodeId : sort === 'numberDesc' ? b.problemId.leetcodeId - a.problemId.leetcodeId : +new Date(b.solvedAt) - +new Date(a.solvedAt)), [items, platform, language, difficulty, search, sort]);
  function removeToast(id: string) { const timer = timers.current.get(id); if (timer) window.clearTimeout(timer); timers.current.delete(id); setToasts(current => current.filter(toast => toast.id !== id)); } function addToast(toast: Toast) { setToasts(current => [...current.filter(item => item.id !== toast.id), toast]); timers.current.set(toast.id, window.setTimeout(() => removeToast(toast.id), 3000)); }
  async function deleteItem(item: SolvedProblem) { const problemId = item.problemId._id; if (deleting.has(problemId)) return; setDeleting(current => new Set(current).add(problemId)); try { const response = await api.deleteProblem(problemId); await load(); addToast({ id: problemId, item, record: response.record, message: 'Problem deleted', restoring: false, error: false }); } catch { addToast({ id: `error-${problemId}-${Date.now()}`, item, record: null, message: "Couldn't delete problem. Please try again.", restoring: false, error: true }); } finally { setDeleting(current => { const next = new Set(current); next.delete(problemId); return next; }); } }
  async function undo(toast: Toast) { if (!toast.record || toast.restoring) return; const timer = timers.current.get(toast.id); if (timer) window.clearTimeout(timer); setToasts(current => current.map(item => item.id === toast.id ? { ...item, restoring: true } : item)); try { await api.restoreProblem(toast.id, toast.record); setItems(current => current.some(item => item._id === toast.item._id) ? current : [...current, toast.item]); removeToast(toast.id); } catch { setToasts(current => current.map(item => item.id === toast.id ? { ...item, record: null, restoring: false, error: true, message: "Couldn't restore problem. Please try again." } : item)); } }
  return <><AppHeader/><main className="shell page-shell"><div className="page-intro"><span className="eyebrow">HISTORY</span><h1>Problems</h1><p className="muted">Every solved problem tracked by LeetMVP.</p></div><section className="panel"><div className="panel-title"><h2>Problem history</h2><div className="controls"><input placeholder="Search name or number…" value={search} onChange={event => setSearch(event.target.value)}/><select value={platform} onChange={event => setPlatform(event.target.value)}><option>All</option><option>LeetCode</option></select><select value={language} onChange={event => setLanguage(event.target.value)}><option>All</option>{languages.map(value => <option key={value}>{value}</option>)}</select><select value={difficulty} onChange={event => setDifficulty(event.target.value)}><option>All</option><option>Easy</option><option>Medium</option><option>Hard</option></select><select value={sort} onChange={event => setSort(event.target.value)}><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="numberAsc">Number ↑</option><option value="numberDesc">Number ↓</option></select></div></div>{loading ? <p className="state">Loading your problems…</p> : error ? <div className="state error">{error}<button onClick={load}>Retry</button></div> : shown.length === 0 ? <p className="state">No solved problems yet.<br/><span className="muted">Start solving on LeetCode to build your history.</span></p> : <div className="table-wrap"><table><thead><tr><th>S.No.</th><th>Question #</th><th>Problem</th><th>Platform</th><th>Difficulty</th><th>Language</th><th>Status</th><th>Solved At</th><th>Action</th></tr></thead><tbody>{shown.map((item, index) => <tr key={item._id} onClick={() => window.open(item.problemId.url, '_blank')}><td>{index + 1}</td><td>{item.problemId.leetcodeId > 0 ? item.problemId.leetcodeId : '—'}</td><td className="title">{item.problemId.title}</td><td>{platformLabel(item.platform)}</td><td><span className={`badge ${item.problemId.difficulty.toLowerCase()}`}>{item.problemId.difficulty}</span></td><td>{languageLabel(item.language)}</td><td>Solved</td><td>{new Date(item.solvedAt).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })}</td><td><button className="delete-button" aria-label={`Delete ${item.problemId.title}`} title="Delete problem" disabled={deleting.has(item._id)} onClick={event => { event.stopPropagation(); void deleteItem(item); }}><TrashIcon/></button></td></tr>)}</tbody></table></div>}</section></main><div className="toast-stack" aria-live="polite">{toasts.map(toast => <div className={`toast ${toast.error ? 'toast-error' : ''}`} key={toast.id} role="status"><span>{toast.message}</span>{toast.record && <button className="toast-undo" disabled={toast.restoring} onClick={() => void undo(toast)}>{toast.restoring ? 'Restoring…' : 'Undo'}</button>}</div>)}</div></>; }
function TrashIcon() { return <svg aria-hidden="true" viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 6h18M8 6V4h8v2m-9 0 1 15h8l1-15M10 10v7m4-7v7"/></svg>; }
